let
    Source = FolderPath,
    #"Filtered Rows" = Table.SelectRows(Source, each Text.Contains([Name], "Annual Qx 202324")),
    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Custom", each let
        // Access the content of the file
        ExcelContent = Excel.Workbook([Content]),
        // Select the first sheet
        FirstSheetData = ExcelContent{0}[Data],
        // Promote the first row to headers
        PromotedHeaders = Table.PromoteHeaders(FirstSheetData, [PromoteAllScalars=true]),
        // Create a list of non-empty header names
        NonEmptyHeaderNames = List.Select(Table.ColumnNames(PromotedHeaders), each _ <> "" and _ <> null and not Text.StartsWith(_, "Column")),
        // Make sure the table includes the 'ST1_NO_Column' column
        // If 'ST1_NO_Column' is not in the headers, this will throw an error
        ST1_NO_Column = List.First(List.Select(NonEmptyHeaderNames, each Text.Contains(_, "ST1_NO"))),
        // Select only columns with non-empty headers
        CleanedTable = Table.SelectColumns(PromotedHeaders, NonEmptyHeaderNames),
        // Filter out rows containing 'ST1_NO_Column'
        FilteredForST1_NO_Column = Table.SelectRows(CleanedTable, each Record.Field(_, ST1_NO_Column) <> null and Record.Field(_, ST1_NO_Column) <> "ST1_NO"),
        // Remove rows where fewer than 3 cells are non-empty
        NonEmptyRows = Table.SelectRows(FilteredForST1_NO_Column, each List.NonNullCount(Record.FieldValues(_)) >= 3),
        // Get the schema of the table to determine column types
        Schema = Table.Schema(NonEmptyRows),
        // Filter the schema to only include record columns
        RecordColumns = Table.SelectRows(Schema, each [Kind] = "record"),
        // Get a list of record column names
        RecordColumnNames = RecordColumns[Name],
        // Replace "#NULL!" values with null in the CleanedTable table
        ReplacedNulls = Table.ReplaceValue(CleanedTable,"#NULL!",null,Replacer.ReplaceValue,NonEmptyHeaderNames),
        // Handle errors in the entire table
        ReplacedErrors = Table.ReplaceErrorValues(ReplacedNulls, List.Transform(Table.ColumnNames(ReplacedNulls), each {_, null}))
    in
        ReplacedErrors
    ),
    #"Expanded Custom" = Table.ExpandTableColumn(#"Added Custom", "Custom", Table.ColumnNames(#"Added Custom"[Custom]{0})),
    #"ChangedTypes" = Table.TransformColumnTypes(#"Expanded Custom", {{"ST1_SID", type text}, {"ST1_NO", type text}}, "en-HK"),
    // Duplicate the ST1_SID column
    #"DuplicatedST1_SID" = Table.DuplicateColumn(#"ChangedTypes", "ST1_SID", "ST1_SID - Copy"),
    // Continue with the rest of your transformation steps...
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"DuplicatedST1_SID", {{"ST1_SID - Copy", type text}, {"ST1_NO", type text}}, "en-HK"),{"ST1_SID - Copy", "ST1_NO"},Combiner.CombineTextByDelimiter("_", QuoteStyle.None),"Merged_ST1_NO"),
    #"Added Custom1" = Table.AddColumn(#"Merged Columns", "ST1_NO", each "HKU" & [Merged_ST1_NO]),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom1",{"Name", "Date accessed", "Folder Path", "Date modified", "ST1_NO", "Merged_ST1_NO", "University", "Version", "PVersion", "ST1_Tier", "ST1_Group", "ST1_PID", "ST1_CID", "ST1_Note", "ST1_Note2", "ST1_P_agr", "ST1_PName", "ST1_CName", "ST1_Sign", "ST1_Date", "ST1_Role", "ST1_RoleO", "ST1_using_ser", "ST1_using_ser_O", "ST1_Dummy1", "ST1_Dummy2", "ST1_CnameC", "ST1_CnameE", "ST1_C_ID", "ST1_B_Day", "ST1_Cgen", "ST1_Addr", "ST1_Dummy3", "ST1_relat_c1", "ST1_relat_c2", "ST1_relat_c3", "ST1_Phone1", "ST1_Phone2", "ST1_Phone3", "ST1_email", "ST1_Sch", "ST1_Grade", "T2_Grade_Other", "ST1_C_att", "ST1_CPOB", "ST1_Chi_Y", "ST1_Chi_M", "ST1_out_Y", "ST1_out_M", "ST1_C_Nat", "ST1_C_Nat_other", "ST1_order", "ST1_Dummy4", "ST1_Num_F", "ST1_Dummy5", "ST1_Num_C", "ST1_Dummy6", "ST1_liveT", "ST1_Dummy7", "ST1_MS", "ST1_Dummy8", "ST1_Mmajor", "ST1_M_Eth", "ST1_M_Eth_Other", "ST1_M_POB", "ST1_M_Cy", "ST1_M_Cm", "ST1_M_Oy", "ST1_M_Om", "ST1_M_DOB", "ST1_M_Can", "ST1_M_PTH", "ST1_M_Eng", "ST1_M_Oth", "ST1_M_Other_Specify", "ST1_M_edu", "ST1_M_Job", "ST1_M_Job_O", "ST1_M_JHr", "ST1_M_Occ", "ST1_M_Occ_O", "ST1_Dummy9", "ST1_Fmajor", "ST1_F_Eth", "ST1_F_Eth_Other", "ST1_F_POB", "ST1_F_Cy", "ST1_F_Cm", "ST1_F_Oy", "ST1_F_Om", "ST1_F_DOB", "ST1_F_Can", "ST1_F_PTH", "ST1_F_Eng", "ST1_F_Oth", "ST1_F_Other_Specify", "ST1_F_edu", "ST1_F_Job", "ST1_F_Job_O", "ST1_F_JHr", "ST1_F_Occ", "ST1_F_Occ_O", "ST1_Dummy10", "ST1_Incom", "ST1_IncoR", "ST1_Dummy11", "ST1_Save", "ST1_SaveR", "ST1_Relia", "ST1_delay", "ST1_Econ", "ST1_Area", "ST1_Space", "ST1_room", "ST1_Resi", "ST1_Resi_Other", "ST1_CSSA", "ST1_Dummy12", "T0_Maj_1", "T0_Maj_2", "T0_Maj_3", "T0_Maj_4", "T0_Maj_5", "T0_Maj_6", "T0_Maj_7", "T0_Maj_8", "T0_Maj_9", "T0_Maj_O", "T0_Maj_O_other", "ST1_FCCan", "ST1_FCPu", "ST1_FCEng", "ST1_FC_O", "ST1_FC_NA", "ST1_FC_Other_specify", "ST1_MCCan", "ST1_MCPu", "ST1_MCEng", "ST1_MC_O", "ST1_MC_NA", "ST1_MC_Other_specify", "ST1_OCCan", "ST1_OCPu", "ST1_OCEng", "ST1_OC_O", "ST1_OC_NA", "ST1_OC_Other_specify", "ST1_MCare", "ST1_Reaso", "ST1_Reason_O", "ST1_Past", "ST1_Past_Program", "ST1_charg", "ST1_At_Y0", "ST1_At_M0", "ST1_At_Y1", "ST1_At_M1", "ST1_Organ", "ST1_Dummy13", "ST1_C_SES", "ST1_HKSES", "ST1_ADHD1", "ST1_ADHD2", "ST1_ADHD3", "ST1_ADHD4", "ST1_Dysle1", "ST1_Dysle2", "ST1_Dysle3", "ST1_Dysle4", "ST1_ASD1", "ST1_ASD2", "ST1_ASD3", "ST1_ASD4", "ST1_SI_1", "ST1_SI_2", "ST1_SI_3", "ST1_SI_4", "ST1_PhyI1", "ST1_PhyI2", "ST1_PhyI3", "ST1_PhyI4", "ST1_VI_1", "ST1_VI_2", "ST1_VI_3", "ST1_VI_4", "ST1_HI_1", "ST1_HI_2", "ST1_HI_3", "ST1_HI_4", "ST1_O_MI_1", "ST1_O_MI_2", "ST1_O_MI_3", "ST1_O_MI_4", "ST1_CD_1", "ST1_CD_2", "ST1_CD_3", "ST1_CD_4", "ST1_O_MI_OS", "ST1_CD_OS", "ST1_F_MI", "ST1_M_MI", "ST1_O_MI", "ST1_F_CD", "ST1_M_CD", "ST1_O_CD", "ST1_Dummy14", "ST1_G_Age", "ST1_weight", "ST1_Itime", "ST1_KGage", "ST1_addTu", "ST1_TuAge", "ST1_TuSes", "ST1_TuDay", "ST1_TuHrs", "ST1_TuLan", "ST1_TuMath", "ST1_TuOth", "ST1_TuOther", "ST1_Dummy15", "ST1_Lan_time", "ST1_Math_time", "ST1_OTu_time", "ST1_Dummy16", "ST1_Dummy17", "ST1_C07a1", "ST1_C07a2", "ST1_Dummy18", "ST1_C07b1", "ST1_C07b2", "ST1_C07b3", "ST1_Dummy19", "ST1_Dummy20", "ST1_C04_a_NightDay_h", "ST1_C04_c_NightDay_min", "ST1_C04_e_NightEnd_h", "ST1_C04_g_NightEnd_min", "ST1_C04_b_MorningDay_h", "ST1_C04_d_MorningDay_min", "ST1_C04_f_MorningEnd_h", "ST1_C04_h_MorningEnd_min", "ST1_C04_i_2a_Fallsleep", "ST1_C04_j_2b_Staysleep", "ST1_C04_k_2c_wakeup", "ST1_C04_L_2d_sleep_quality", "ST1_Dummy21", "ST1_OC02_a_Not_KG_Morning_Day_Hr", "ST1_OC02_b_Not_KG_Morning_Day_mins", "ST1_OC02_c_Not_KG_Morning_weekend_Hr", "ST1_OC02_d_Not_KG_Morning_weekend_mins", "ST1_OC02_e_Not_KG_afternoon_Day_Hr", "ST1_OC02_f_Not_KG_afternoon_Day_Mins", "ST1_OC02_g_Not_KG_afternoon_weekend_Hr", "ST1_OC02_h_Not_KG_afternoon_weekend_mins", "ST1_OC02_i_Not_KG_night_Day_Hr", "ST1_OC02_j_Not_KG_night_Day_mins", "ST1_OC02_k_Not_KG_night_weekend_Hr", "ST1_OC02_L_Not_KG_night_weekend_mins", "ST1_OC02_m_KG_Morning_Day_Hr", "ST1_OC02_n_KG_Morning_Day_mins", "ST1_OC02_o_KG_afternoon_Day_Hr", "ST1_OC02_p_KG_afternoon_Day_Mins", "ST1_Dummy22", "ST1_Vis_1_test", "ST1_Vis_1a_public", "ST1_Vis_1b_Private", "ST1_Dummy23", "ST1_Vis2a_Shortsightedness", "ST1_Vis2i_Years_old_Shortsightedness", "ST1_Vis2q_Lens_Shortsightedness", "ST1_Vis2_Other_1", "ST1_Vis2b_Longsightedness", "ST1_Vis2j_Years_old_Longsightedness", "ST1_Vis2r_Lens_Longsightedness", "ST1_Vis2_Other_2", "ST1_Vis2c_Astigmatism", "ST1_Vis2k_Years_old_Astigmatism", "ST1_Vis2s_Lens_Astigmatism", "ST1_Vis2_Other_3", "ST1_Vis2d_Squint", "ST1_Vis2L_Years_old_Squint", "ST1_Vis2t_Lens_Squint", "ST1_Vis2_Other_4", "ST1_Vis2e_Congenital_cataract", "ST1_Vis2m_Years_old_Congenital_cataract", "ST1_Vis2u_Lens_Congenital_cataract", "ST1_Vis2_Other_5", "ST1_Vis2f_Colour_blindness", "ST1_Vis2n_Years_old_Colour_blindness", "ST1_Vis2v_Lens_Colour_blindness", "ST1_Vis2_Other_6", "ST1_Vis2g_Amblyopia", "ST1_Vis2o_Years_old_Amblyopia", "ST1_Vis2w_Lens_Amblyopia", "ST1_Vis2_Other_7", "ST1_Vis2h_Others", "ST1_Vis2p_Years_old_Others", "ST1_Vis2x_Lens_Others", "ST1_Vis2_Other_8", "ST1_Dummy24", "ST1_C02_1", "ST1_C02_2", "ST1_C02_3", "ST1_C02_4", "ST1_C02_5", "ST1_C02_6", "ST1_C02_7", "ST1_C02_8", "ST1_C02_9", "ST1_C02_10", "ST1_C02_11", "ST1_C02_12", "ST1_C02_13", "ST1_C02_14", "ST1_C02_15", "ST1_C02_16", "ST1_C02_17", "ST1_C02_18", "ST1_C02_19", "ST1_C02_20", "ST1_C02_21", "ST1_C02_22", "ST1_C02_23", "ST1_C02_24", "ST1_C02_25", "ST1_Dummy25", "ST1_Dummy26", "ST1_CPR1", "ST1_CPR2", "ST1_CPR3", "ST1_CPR4", "ST1_CPR5", "ST1_CPR6", "ST1_CPR7", "ST1_CPR8", "ST1_CPR9", "ST1_CPR10", "ST1_CPR11", "ST1_CPR12", "ST1_CPR13", "ST1_CPR14", "ST1_CPR15", "ST1_Dummy27", "ST1_CPCI1", "ST1_CPCI2", "ST1_CPCI3", "ST1_CPCI4", "ST1_CPCI5", "ST1_CPCI6", "ST1_CPCI7", "ST1_CPCI8", "ST1_Dummy28", "ST1_Dummy29", "ST1_CAR1", "ST1_CAR2", "ST1_CAR3", "ST1_CAR4", "ST1_CAR5", "ST1_CAR6", "ST1_CAR7", "ST1_CAR8", "ST1_CAR9", "ST1_CAR10", "ST1_CAR11", "ST1_CAR12", "ST1_CAR13", "ST1_CAR14", "ST1_CAR15", "ST1_Dummy30", "ST1_ERC1", "ST1_ERC2", "ST1_ERC3", "ST1_ERC4", "ST1_ERC5", "ST1_ERC6", "ST1_ERC7", "ST1_ERC8", "ST1_ERC9", "ST1_ERC10", "ST1_ERC11", "ST1_ERC12", "ST1_ERC13", "ST1_ERC14", "ST1_ERC15", "ST1_ERC16", "ST1_ERC17", "ST1_ERC18", "ST1_ERC19", "ST1_ERC20", "ST1_ERC21", "ST1_ERC22", "ST1_ERC23", "ST1_ERC24", "ST1_Dummy31", "ST1_Dummy32", "ST1_PBQ1", "ST1_PBQ2", "ST1_PBQ3", "ST1_PBQ4", "ST1_PBQ5", "ST1_PBQ6", "ST1_PBQ7", "ST1_PBQ8", "ST1_PBQ9", "ST1_PBQ10", "ST1_PBQ11", "ST1_PBQ12", "ST1_PBQ13", "ST1_PBQ14", "ST1_PBQ15", "ST1_PBQ16", "ST1_PBQ17", "ST1_PBQ18", "ST1_PBQ19", "ST1_PBQ20", "ST1_PBQ21", "ST1_PBQ22", "ST1_PBQ23", "ST1_PBQ24", "ST1_PBQ25", "ST1_PBQ26", "ST1_Dummy33", "ST1_Dummy34", "ST1_C03_1", "ST1_C03_2", "ST1_C03_3", "ST1_C03_4", "ST1_C03_5", "ST1_C03_6", "ST1_C03_7", "ST1_C03_8", "ST1_C03_9", "ST1_C03_10", "ST1_C03_11", "ST1_C03_12", "ST1_C03_13", "ST1_C03_14", "ST1_C03_15", "ST1_C03_16", "ST1_C03_17", "ST1_C03_18", "ST1_C03_19", "ST1_C03_20", "ST1_C03_21", "ST1_C03_22", "ST1_C03_23", "ST1_C03_24", "ST1_C03_25", "ST1_C03_26", "ST1_C03_27", "ST1_Dummy35", "ST1_C05_1", "ST1_C05_2", "ST1_C05_3", "ST1_C05_4", "ST1_C05_5", "ST1_C05_6", "ST1_C05_7", "ST1_C05_8", "ST1_C05_9", "ST1_C05_10", "ST1_C05_11", "ST1_C05_12", "ST1_C05_13", "ST1_C05_14", "ST1_C05_15", "ST1_C05_16", "ST1_C05_17", "ST1_Dummy36", "ST1_SBp1", "ST1_SBp2", "ST1_SBp3", "ST1_SBp4", "ST1_SBp5", "ST1_SBp6", "ST1_SBp7", "ST1_SBp8", "ST1_SBp9", "ST1_SBp10", "ST1_SBp11", "ST1_SBp12", "ST1_SBp13", "ST1_SBp14", "ST1_SBc1", "ST1_SBc2", "ST1_SBc3", "ST1_SBc4", "ST1_SBc5", "ST1_SBc6", "ST1_SBc7", "ST1_SBc8", "ST1_SBc9", "ST1_SBc10", "ST1_SBc11", "ST1_SBc12", "ST1_SBc13", "ST1_SBc14", "ST1_Dummy37", "ST1_DASS1", "ST1_DASS2", "ST1_DASS3", "ST1_DASS4", "ST1_DASS5", "ST1_DASS6", "ST1_DASS7", "ST1_DASS8", "ST1_DASS9", "ST1_DASS10", "ST1_DASS11", "ST1_DASS12", "ST1_DASS13", "ST1_DASS14", "ST1_DASS15", "ST1_DASS16", "ST1_DASS17", "ST1_DASS18", "ST1_DASS19", "ST1_DASS20", "ST1_DASS21", "ST1_Dummy38", "ST1_TCF1", "ST1_TCF2", "ST1_TCF3", "ST1_TCF4", "ST1_TCF5", "ST1_TCF6", "ST1_TCF7", "ST1_TCF8"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns1",{"Merged_ST1_NO", "Content", "Extension", "Date created", "Attributes"}),
    #"Added Custom2" = Table.AddColumn(#"Removed Columns2", "ST1_SID SXXX", each if Text.Length([ST1_SID]) = 1 then "S00" & [ST1_SID] 
    else if Text.Length([ST1_SID]) = 2 then "S0" & [ST1_SID]
    else "S" & [ST1_SID]),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom2",{"Name", "Date accessed", "Folder Path", "Date modified", "ST1_NO", "University", "Version", "PVersion", "ST1_Tier", "ST1_SID", "ST1_SID SXXX", "ST1_Group", "ST1_PID", "ST1_CID", "ST1_Note", "ST1_Note2", "ST1_P_agr", "ST1_PName", "ST1_CName", "ST1_Sign", "ST1_Date", "ST1_Role", "ST1_RoleO", "ST1_using_ser", "ST1_using_ser_O", "ST1_Dummy1", "ST1_Dummy2", "ST1_CnameC", "ST1_CnameE", "ST1_C_ID", "ST1_B_Day", "ST1_Cgen", "ST1_Addr", "ST1_Dummy3", "ST1_relat_c1", "ST1_relat_c2", "ST1_relat_c3", "ST1_Phone1", "ST1_Phone2", "ST1_Phone3", "ST1_email", "ST1_Sch", "ST1_Grade", "T2_Grade_Other", "ST1_C_att", "ST1_CPOB", "ST1_Chi_Y", "ST1_Chi_M", "ST1_out_Y", "ST1_out_M", "ST1_C_Nat", "ST1_C_Nat_other", "ST1_order", "ST1_Dummy4", "ST1_Num_F", "ST1_Dummy5", "ST1_Num_C", "ST1_Dummy6", "ST1_liveT", "ST1_Dummy7", "ST1_MS", "ST1_Dummy8", "ST1_Mmajor", "ST1_M_Eth", "ST1_M_Eth_Other", "ST1_M_POB", "ST1_M_Cy", "ST1_M_Cm", "ST1_M_Oy", "ST1_M_Om", "ST1_M_DOB", "ST1_M_Can", "ST1_M_PTH", "ST1_M_Eng", "ST1_M_Oth", "ST1_M_Other_Specify", "ST1_M_edu", "ST1_M_Job", "ST1_M_Job_O", "ST1_M_JHr", "ST1_M_Occ", "ST1_M_Occ_O", "ST1_Dummy9", "ST1_Fmajor", "ST1_F_Eth", "ST1_F_Eth_Other", "ST1_F_POB", "ST1_F_Cy", "ST1_F_Cm", "ST1_F_Oy", "ST1_F_Om", "ST1_F_DOB", "ST1_F_Can", "ST1_F_PTH", "ST1_F_Eng", "ST1_F_Oth", "ST1_F_Other_Specify", "ST1_F_edu", "ST1_F_Job", "ST1_F_Job_O", "ST1_F_JHr", "ST1_F_Occ", "ST1_F_Occ_O", "ST1_Dummy10", "ST1_Incom", "ST1_IncoR", "ST1_Dummy11", "ST1_Save", "ST1_SaveR", "ST1_Relia", "ST1_delay", "ST1_Econ", "ST1_Area", "ST1_Space", "ST1_room", "ST1_Resi", "ST1_Resi_Other", "ST1_CSSA", "ST1_Dummy12", "T0_Maj_1", "T0_Maj_2", "T0_Maj_3", "T0_Maj_4", "T0_Maj_5", "T0_Maj_6", "T0_Maj_7", "T0_Maj_8", "T0_Maj_9", "T0_Maj_O", "T0_Maj_O_other", "ST1_FCCan", "ST1_FCPu", "ST1_FCEng", "ST1_FC_O", "ST1_FC_NA", "ST1_FC_Other_specify", "ST1_MCCan", "ST1_MCPu", "ST1_MCEng", "ST1_MC_O", "ST1_MC_NA", "ST1_MC_Other_specify", "ST1_OCCan", "ST1_OCPu", "ST1_OCEng", "ST1_OC_O", "ST1_OC_NA", "ST1_OC_Other_specify", "ST1_MCare", "ST1_Reaso", "ST1_Reason_O", "ST1_Past", "ST1_Past_Program", "ST1_charg", "ST1_At_Y0", "ST1_At_M0", "ST1_At_Y1", "ST1_At_M1", "ST1_Organ", "ST1_Dummy13", "ST1_C_SES", "ST1_HKSES", "ST1_ADHD1", "ST1_ADHD2", "ST1_ADHD3", "ST1_ADHD4", "ST1_Dysle1", "ST1_Dysle2", "ST1_Dysle3", "ST1_Dysle4", "ST1_ASD1", "ST1_ASD2", "ST1_ASD3", "ST1_ASD4", "ST1_SI_1", "ST1_SI_2", "ST1_SI_3", "ST1_SI_4", "ST1_PhyI1", "ST1_PhyI2", "ST1_PhyI3", "ST1_PhyI4", "ST1_VI_1", "ST1_VI_2", "ST1_VI_3", "ST1_VI_4", "ST1_HI_1", "ST1_HI_2", "ST1_HI_3", "ST1_HI_4", "ST1_O_MI_1", "ST1_O_MI_2", "ST1_O_MI_3", "ST1_O_MI_4", "ST1_CD_1", "ST1_CD_2", "ST1_CD_3", "ST1_CD_4", "ST1_O_MI_OS", "ST1_CD_OS", "ST1_F_MI", "ST1_M_MI", "ST1_O_MI", "ST1_F_CD", "ST1_M_CD", "ST1_O_CD", "ST1_Dummy14", "ST1_G_Age", "ST1_weight", "ST1_Itime", "ST1_KGage", "ST1_addTu", "ST1_TuAge", "ST1_TuSes", "ST1_TuDay", "ST1_TuHrs", "ST1_TuLan", "ST1_TuMath", "ST1_TuOth", "ST1_TuOther", "ST1_Dummy15", "ST1_Lan_time", "ST1_Math_time", "ST1_OTu_time", "ST1_Dummy16", "ST1_Dummy17", "ST1_C07a1", "ST1_C07a2", "ST1_Dummy18", "ST1_C07b1", "ST1_C07b2", "ST1_C07b3", "ST1_Dummy19", "ST1_Dummy20", "ST1_C04_a_NightDay_h", "ST1_C04_c_NightDay_min", "ST1_C04_e_NightEnd_h", "ST1_C04_g_NightEnd_min", "ST1_C04_b_MorningDay_h", "ST1_C04_d_MorningDay_min", "ST1_C04_f_MorningEnd_h", "ST1_C04_h_MorningEnd_min", "ST1_C04_i_2a_Fallsleep", "ST1_C04_j_2b_Staysleep", "ST1_C04_k_2c_wakeup", "ST1_C04_L_2d_sleep_quality", "ST1_Dummy21", "ST1_OC02_a_Not_KG_Morning_Day_Hr", "ST1_OC02_b_Not_KG_Morning_Day_mins", "ST1_OC02_c_Not_KG_Morning_weekend_Hr", "ST1_OC02_d_Not_KG_Morning_weekend_mins", "ST1_OC02_e_Not_KG_afternoon_Day_Hr", "ST1_OC02_f_Not_KG_afternoon_Day_Mins", "ST1_OC02_g_Not_KG_afternoon_weekend_Hr", "ST1_OC02_h_Not_KG_afternoon_weekend_mins", "ST1_OC02_i_Not_KG_night_Day_Hr", "ST1_OC02_j_Not_KG_night_Day_mins", "ST1_OC02_k_Not_KG_night_weekend_Hr", "ST1_OC02_L_Not_KG_night_weekend_mins", "ST1_OC02_m_KG_Morning_Day_Hr", "ST1_OC02_n_KG_Morning_Day_mins", "ST1_OC02_o_KG_afternoon_Day_Hr", "ST1_OC02_p_KG_afternoon_Day_Mins", "ST1_Dummy22", "ST1_Vis_1_test", "ST1_Vis_1a_public", "ST1_Vis_1b_Private", "ST1_Dummy23", "ST1_Vis2a_Shortsightedness", "ST1_Vis2i_Years_old_Shortsightedness", "ST1_Vis2q_Lens_Shortsightedness", "ST1_Vis2_Other_1", "ST1_Vis2b_Longsightedness", "ST1_Vis2j_Years_old_Longsightedness", "ST1_Vis2r_Lens_Longsightedness", "ST1_Vis2_Other_2", "ST1_Vis2c_Astigmatism", "ST1_Vis2k_Years_old_Astigmatism", "ST1_Vis2s_Lens_Astigmatism", "ST1_Vis2_Other_3", "ST1_Vis2d_Squint", "ST1_Vis2L_Years_old_Squint", "ST1_Vis2t_Lens_Squint", "ST1_Vis2_Other_4", "ST1_Vis2e_Congenital_cataract", "ST1_Vis2m_Years_old_Congenital_cataract", "ST1_Vis2u_Lens_Congenital_cataract", "ST1_Vis2_Other_5", "ST1_Vis2f_Colour_blindness", "ST1_Vis2n_Years_old_Colour_blindness", "ST1_Vis2v_Lens_Colour_blindness", "ST1_Vis2_Other_6", "ST1_Vis2g_Amblyopia", "ST1_Vis2o_Years_old_Amblyopia", "ST1_Vis2w_Lens_Amblyopia", "ST1_Vis2_Other_7", "ST1_Vis2h_Others", "ST1_Vis2p_Years_old_Others", "ST1_Vis2x_Lens_Others", "ST1_Vis2_Other_8", "ST1_Dummy24", "ST1_C02_1", "ST1_C02_2", "ST1_C02_3", "ST1_C02_4", "ST1_C02_5", "ST1_C02_6", "ST1_C02_7", "ST1_C02_8", "ST1_C02_9", "ST1_C02_10", "ST1_C02_11", "ST1_C02_12", "ST1_C02_13", "ST1_C02_14", "ST1_C02_15", "ST1_C02_16", "ST1_C02_17", "ST1_C02_18", "ST1_C02_19", "ST1_C02_20", "ST1_C02_21", "ST1_C02_22", "ST1_C02_23", "ST1_C02_24", "ST1_C02_25", "ST1_Dummy25", "ST1_Dummy26", "ST1_CPR1", "ST1_CPR2", "ST1_CPR3", "ST1_CPR4", "ST1_CPR5", "ST1_CPR6", "ST1_CPR7", "ST1_CPR8", "ST1_CPR9", "ST1_CPR10", "ST1_CPR11", "ST1_CPR12", "ST1_CPR13", "ST1_CPR14", "ST1_CPR15", "ST1_Dummy27", "ST1_CPCI1", "ST1_CPCI2", "ST1_CPCI3", "ST1_CPCI4", "ST1_CPCI5", "ST1_CPCI6", "ST1_CPCI7", "ST1_CPCI8", "ST1_Dummy28", "ST1_Dummy29", "ST1_CAR1", "ST1_CAR2", "ST1_CAR3", "ST1_CAR4", "ST1_CAR5", "ST1_CAR6", "ST1_CAR7", "ST1_CAR8", "ST1_CAR9", "ST1_CAR10", "ST1_CAR11", "ST1_CAR12", "ST1_CAR13", "ST1_CAR14", "ST1_CAR15", "ST1_Dummy30", "ST1_ERC1", "ST1_ERC2", "ST1_ERC3", "ST1_ERC4", "ST1_ERC5", "ST1_ERC6", "ST1_ERC7", "ST1_ERC8", "ST1_ERC9", "ST1_ERC10", "ST1_ERC11", "ST1_ERC12", "ST1_ERC13", "ST1_ERC14", "ST1_ERC15", "ST1_ERC16", "ST1_ERC17", "ST1_ERC18", "ST1_ERC19", "ST1_ERC20", "ST1_ERC21", "ST1_ERC22", "ST1_ERC23", "ST1_ERC24", "ST1_Dummy31", "ST1_Dummy32", "ST1_PBQ1", "ST1_PBQ2", "ST1_PBQ3", "ST1_PBQ4", "ST1_PBQ5", "ST1_PBQ6", "ST1_PBQ7", "ST1_PBQ8", "ST1_PBQ9", "ST1_PBQ10", "ST1_PBQ11", "ST1_PBQ12", "ST1_PBQ13", "ST1_PBQ14", "ST1_PBQ15", "ST1_PBQ16", "ST1_PBQ17", "ST1_PBQ18", "ST1_PBQ19", "ST1_PBQ20", "ST1_PBQ21", "ST1_PBQ22", "ST1_PBQ23", "ST1_PBQ24", "ST1_PBQ25", "ST1_PBQ26", "ST1_Dummy33", "ST1_Dummy34", "ST1_C03_1", "ST1_C03_2", "ST1_C03_3", "ST1_C03_4", "ST1_C03_5", "ST1_C03_6", "ST1_C03_7", "ST1_C03_8", "ST1_C03_9", "ST1_C03_10", "ST1_C03_11", "ST1_C03_12", "ST1_C03_13", "ST1_C03_14", "ST1_C03_15", "ST1_C03_16", "ST1_C03_17", "ST1_C03_18", "ST1_C03_19", "ST1_C03_20", "ST1_C03_21", "ST1_C03_22", "ST1_C03_23", "ST1_C03_24", "ST1_C03_25", "ST1_C03_26", "ST1_C03_27", "ST1_Dummy35", "ST1_C05_1", "ST1_C05_2", "ST1_C05_3", "ST1_C05_4", "ST1_C05_5", "ST1_C05_6", "ST1_C05_7", "ST1_C05_8", "ST1_C05_9", "ST1_C05_10", "ST1_C05_11", "ST1_C05_12", "ST1_C05_13", "ST1_C05_14", "ST1_C05_15", "ST1_C05_16", "ST1_C05_17", "ST1_Dummy36", "ST1_SBp1", "ST1_SBp2", "ST1_SBp3", "ST1_SBp4", "ST1_SBp5", "ST1_SBp6", "ST1_SBp7", "ST1_SBp8", "ST1_SBp9", "ST1_SBp10", "ST1_SBp11", "ST1_SBp12", "ST1_SBp13", "ST1_SBp14", "ST1_SBc1", "ST1_SBc2", "ST1_SBc3", "ST1_SBc4", "ST1_SBc5", "ST1_SBc6", "ST1_SBc7", "ST1_SBc8", "ST1_SBc9", "ST1_SBc10", "ST1_SBc11", "ST1_SBc12", "ST1_SBc13", "ST1_SBc14", "ST1_Dummy37", "ST1_DASS1", "ST1_DASS2", "ST1_DASS3", "ST1_DASS4", "ST1_DASS5", "ST1_DASS6", "ST1_DASS7", "ST1_DASS8", "ST1_DASS9", "ST1_DASS10", "ST1_DASS11", "ST1_DASS12", "ST1_DASS13", "ST1_DASS14", "ST1_DASS15", "ST1_DASS16", "ST1_DASS17", "ST1_DASS18", "ST1_DASS19", "ST1_DASS20", "ST1_DASS21", "ST1_Dummy38", "ST1_TCF1", "ST1_TCF2", "ST1_TCF3", "ST1_TCF4", "ST1_TCF5", "ST1_TCF6", "ST1_TCF7", "ST1_TCF8"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"ST1_SID"}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns",{"Name", "Date accessed", "Folder Path", "Date modified", "ST1_NO", "University", "Version", "PVersion", "ST1_Tier", "ST1_Group", "ST1_SID SXXX", "ST1_PID", "ST1_CID", "ST1_Note", "ST1_Note2", "ST1_P_agr", "ST1_PName", "ST1_CName", "ST1_Sign", "ST1_Date", "ST1_Role", "ST1_RoleO", "ST1_using_ser", "ST1_using_ser_O", "ST1_Dummy1", "ST1_Dummy2", "ST1_CnameC", "ST1_CnameE", "ST1_C_ID", "ST1_B_Day", "ST1_Cgen", "ST1_Addr", "ST1_Dummy3", "ST1_relat_c1", "ST1_relat_c2", "ST1_relat_c3", "ST1_Phone1", "ST1_Phone2", "ST1_Phone3", "ST1_email", "ST1_Sch", "ST1_Grade", "T2_Grade_Other", "ST1_C_att", "ST1_CPOB", "ST1_Chi_Y", "ST1_Chi_M", "ST1_out_Y", "ST1_out_M", "ST1_C_Nat", "ST1_C_Nat_other", "ST1_order", "ST1_Dummy4", "ST1_Num_F", "ST1_Dummy5", "ST1_Num_C", "ST1_Dummy6", "ST1_liveT", "ST1_Dummy7", "ST1_MS", "ST1_Dummy8", "ST1_Mmajor", "ST1_M_Eth", "ST1_M_Eth_Other", "ST1_M_POB", "ST1_M_Cy", "ST1_M_Cm", "ST1_M_Oy", "ST1_M_Om", "ST1_M_DOB", "ST1_M_Can", "ST1_M_PTH", "ST1_M_Eng", "ST1_M_Oth", "ST1_M_Other_Specify", "ST1_M_edu", "ST1_M_Job", "ST1_M_Job_O", "ST1_M_JHr", "ST1_M_Occ", "ST1_M_Occ_O", "ST1_Dummy9", "ST1_Fmajor", "ST1_F_Eth", "ST1_F_Eth_Other", "ST1_F_POB", "ST1_F_Cy", "ST1_F_Cm", "ST1_F_Oy", "ST1_F_Om", "ST1_F_DOB", "ST1_F_Can", "ST1_F_PTH", "ST1_F_Eng", "ST1_F_Oth", "ST1_F_Other_Specify", "ST1_F_edu", "ST1_F_Job", "ST1_F_Job_O", "ST1_F_JHr", "ST1_F_Occ", "ST1_F_Occ_O", "ST1_Dummy10", "ST1_Incom", "ST1_IncoR", "ST1_Dummy11", "ST1_Save", "ST1_SaveR", "ST1_Relia", "ST1_delay", "ST1_Econ", "ST1_Area", "ST1_Space", "ST1_room", "ST1_Resi", "ST1_Resi_Other", "ST1_CSSA", "ST1_Dummy12", "T0_Maj_1", "T0_Maj_2", "T0_Maj_3", "T0_Maj_4", "T0_Maj_5", "T0_Maj_6", "T0_Maj_7", "T0_Maj_8", "T0_Maj_9", "T0_Maj_O", "T0_Maj_O_other", "ST1_FCCan", "ST1_FCPu", "ST1_FCEng", "ST1_FC_O", "ST1_FC_NA", "ST1_FC_Other_specify", "ST1_MCCan", "ST1_MCPu", "ST1_MCEng", "ST1_MC_O", "ST1_MC_NA", "ST1_MC_Other_specify", "ST1_OCCan", "ST1_OCPu", "ST1_OCEng", "ST1_OC_O", "ST1_OC_NA", "ST1_OC_Other_specify", "ST1_MCare", "ST1_Reaso", "ST1_Reason_O", "ST1_Past", "ST1_Past_Program", "ST1_charg", "ST1_At_Y0", "ST1_At_M0", "ST1_At_Y1", "ST1_At_M1", "ST1_Organ", "ST1_Dummy13", "ST1_C_SES", "ST1_HKSES", "ST1_ADHD1", "ST1_ADHD2", "ST1_ADHD3", "ST1_ADHD4", "ST1_Dysle1", "ST1_Dysle2", "ST1_Dysle3", "ST1_Dysle4", "ST1_ASD1", "ST1_ASD2", "ST1_ASD3", "ST1_ASD4", "ST1_SI_1", "ST1_SI_2", "ST1_SI_3", "ST1_SI_4", "ST1_PhyI1", "ST1_PhyI2", "ST1_PhyI3", "ST1_PhyI4", "ST1_VI_1", "ST1_VI_2", "ST1_VI_3", "ST1_VI_4", "ST1_HI_1", "ST1_HI_2", "ST1_HI_3", "ST1_HI_4", "ST1_O_MI_1", "ST1_O_MI_2", "ST1_O_MI_3", "ST1_O_MI_4", "ST1_CD_1", "ST1_CD_2", "ST1_CD_3", "ST1_CD_4", "ST1_O_MI_OS", "ST1_CD_OS", "ST1_F_MI", "ST1_M_MI", "ST1_O_MI", "ST1_F_CD", "ST1_M_CD", "ST1_O_CD", "ST1_Dummy14", "ST1_G_Age", "ST1_weight", "ST1_Itime", "ST1_KGage", "ST1_addTu", "ST1_TuAge", "ST1_TuSes", "ST1_TuDay", "ST1_TuHrs", "ST1_TuLan", "ST1_TuMath", "ST1_TuOth", "ST1_TuOther", "ST1_Dummy15", "ST1_Lan_time", "ST1_Math_time", "ST1_OTu_time", "ST1_Dummy16", "ST1_Dummy17", "ST1_C07a1", "ST1_C07a2", "ST1_Dummy18", "ST1_C07b1", "ST1_C07b2", "ST1_C07b3", "ST1_Dummy19", "ST1_Dummy20", "ST1_C04_a_NightDay_h", "ST1_C04_c_NightDay_min", "ST1_C04_e_NightEnd_h", "ST1_C04_g_NightEnd_min", "ST1_C04_b_MorningDay_h", "ST1_C04_d_MorningDay_min", "ST1_C04_f_MorningEnd_h", "ST1_C04_h_MorningEnd_min", "ST1_C04_i_2a_Fallsleep", "ST1_C04_j_2b_Staysleep", "ST1_C04_k_2c_wakeup", "ST1_C04_L_2d_sleep_quality", "ST1_Dummy21", "ST1_OC02_a_Not_KG_Morning_Day_Hr", "ST1_OC02_b_Not_KG_Morning_Day_mins", "ST1_OC02_c_Not_KG_Morning_weekend_Hr", "ST1_OC02_d_Not_KG_Morning_weekend_mins", "ST1_OC02_e_Not_KG_afternoon_Day_Hr", "ST1_OC02_f_Not_KG_afternoon_Day_Mins", "ST1_OC02_g_Not_KG_afternoon_weekend_Hr", "ST1_OC02_h_Not_KG_afternoon_weekend_mins", "ST1_OC02_i_Not_KG_night_Day_Hr", "ST1_OC02_j_Not_KG_night_Day_mins", "ST1_OC02_k_Not_KG_night_weekend_Hr", "ST1_OC02_L_Not_KG_night_weekend_mins", "ST1_OC02_m_KG_Morning_Day_Hr", "ST1_OC02_n_KG_Morning_Day_mins", "ST1_OC02_o_KG_afternoon_Day_Hr", "ST1_OC02_p_KG_afternoon_Day_Mins", "ST1_Dummy22", "ST1_Vis_1_test", "ST1_Vis_1a_public", "ST1_Vis_1b_Private", "ST1_Dummy23", "ST1_Vis2a_Shortsightedness", "ST1_Vis2i_Years_old_Shortsightedness", "ST1_Vis2q_Lens_Shortsightedness", "ST1_Vis2_Other_1", "ST1_Vis2b_Longsightedness", "ST1_Vis2j_Years_old_Longsightedness", "ST1_Vis2r_Lens_Longsightedness", "ST1_Vis2_Other_2", "ST1_Vis2c_Astigmatism", "ST1_Vis2k_Years_old_Astigmatism", "ST1_Vis2s_Lens_Astigmatism", "ST1_Vis2_Other_3", "ST1_Vis2d_Squint", "ST1_Vis2L_Years_old_Squint", "ST1_Vis2t_Lens_Squint", "ST1_Vis2_Other_4", "ST1_Vis2e_Congenital_cataract", "ST1_Vis2m_Years_old_Congenital_cataract", "ST1_Vis2u_Lens_Congenital_cataract", "ST1_Vis2_Other_5", "ST1_Vis2f_Colour_blindness", "ST1_Vis2n_Years_old_Colour_blindness", "ST1_Vis2v_Lens_Colour_blindness", "ST1_Vis2_Other_6", "ST1_Vis2g_Amblyopia", "ST1_Vis2o_Years_old_Amblyopia", "ST1_Vis2w_Lens_Amblyopia", "ST1_Vis2_Other_7", "ST1_Vis2h_Others", "ST1_Vis2p_Years_old_Others", "ST1_Vis2x_Lens_Others", "ST1_Vis2_Other_8", "ST1_Dummy24", "ST1_C02_1", "ST1_C02_2", "ST1_C02_3", "ST1_C02_4", "ST1_C02_5", "ST1_C02_6", "ST1_C02_7", "ST1_C02_8", "ST1_C02_9", "ST1_C02_10", "ST1_C02_11", "ST1_C02_12", "ST1_C02_13", "ST1_C02_14", "ST1_C02_15", "ST1_C02_16", "ST1_C02_17", "ST1_C02_18", "ST1_C02_19", "ST1_C02_20", "ST1_C02_21", "ST1_C02_22", "ST1_C02_23", "ST1_C02_24", "ST1_C02_25", "ST1_Dummy25", "ST1_Dummy26", "ST1_CPR1", "ST1_CPR2", "ST1_CPR3", "ST1_CPR4", "ST1_CPR5", "ST1_CPR6", "ST1_CPR7", "ST1_CPR8", "ST1_CPR9", "ST1_CPR10", "ST1_CPR11", "ST1_CPR12", "ST1_CPR13", "ST1_CPR14", "ST1_CPR15", "ST1_Dummy27", "ST1_CPCI1", "ST1_CPCI2", "ST1_CPCI3", "ST1_CPCI4", "ST1_CPCI5", "ST1_CPCI6", "ST1_CPCI7", "ST1_CPCI8", "ST1_Dummy28", "ST1_Dummy29", "ST1_CAR1", "ST1_CAR2", "ST1_CAR3", "ST1_CAR4", "ST1_CAR5", "ST1_CAR6", "ST1_CAR7", "ST1_CAR8", "ST1_CAR9", "ST1_CAR10", "ST1_CAR11", "ST1_CAR12", "ST1_CAR13", "ST1_CAR14", "ST1_CAR15", "ST1_Dummy30", "ST1_ERC1", "ST1_ERC2", "ST1_ERC3", "ST1_ERC4", "ST1_ERC5", "ST1_ERC6", "ST1_ERC7", "ST1_ERC8", "ST1_ERC9", "ST1_ERC10", "ST1_ERC11", "ST1_ERC12", "ST1_ERC13", "ST1_ERC14", "ST1_ERC15", "ST1_ERC16", "ST1_ERC17", "ST1_ERC18", "ST1_ERC19", "ST1_ERC20", "ST1_ERC21", "ST1_ERC22", "ST1_ERC23", "ST1_ERC24", "ST1_Dummy31", "ST1_Dummy32", "ST1_PBQ1", "ST1_PBQ2", "ST1_PBQ3", "ST1_PBQ4", "ST1_PBQ5", "ST1_PBQ6", "ST1_PBQ7", "ST1_PBQ8", "ST1_PBQ9", "ST1_PBQ10", "ST1_PBQ11", "ST1_PBQ12", "ST1_PBQ13", "ST1_PBQ14", "ST1_PBQ15", "ST1_PBQ16", "ST1_PBQ17", "ST1_PBQ18", "ST1_PBQ19", "ST1_PBQ20", "ST1_PBQ21", "ST1_PBQ22", "ST1_PBQ23", "ST1_PBQ24", "ST1_PBQ25", "ST1_PBQ26", "ST1_Dummy33", "ST1_Dummy34", "ST1_C03_1", "ST1_C03_2", "ST1_C03_3", "ST1_C03_4", "ST1_C03_5", "ST1_C03_6", "ST1_C03_7", "ST1_C03_8", "ST1_C03_9", "ST1_C03_10", "ST1_C03_11", "ST1_C03_12", "ST1_C03_13", "ST1_C03_14", "ST1_C03_15", "ST1_C03_16", "ST1_C03_17", "ST1_C03_18", "ST1_C03_19", "ST1_C03_20", "ST1_C03_21", "ST1_C03_22", "ST1_C03_23", "ST1_C03_24", "ST1_C03_25", "ST1_C03_26", "ST1_C03_27", "ST1_Dummy35", "ST1_C05_1", "ST1_C05_2", "ST1_C05_3", "ST1_C05_4", "ST1_C05_5", "ST1_C05_6", "ST1_C05_7", "ST1_C05_8", "ST1_C05_9", "ST1_C05_10", "ST1_C05_11", "ST1_C05_12", "ST1_C05_13", "ST1_C05_14", "ST1_C05_15", "ST1_C05_16", "ST1_C05_17", "ST1_Dummy36", "ST1_SBp1", "ST1_SBp2", "ST1_SBp3", "ST1_SBp4", "ST1_SBp5", "ST1_SBp6", "ST1_SBp7", "ST1_SBp8", "ST1_SBp9", "ST1_SBp10", "ST1_SBp11", "ST1_SBp12", "ST1_SBp13", "ST1_SBp14", "ST1_SBc1", "ST1_SBc2", "ST1_SBc3", "ST1_SBc4", "ST1_SBc5", "ST1_SBc6", "ST1_SBc7", "ST1_SBc8", "ST1_SBc9", "ST1_SBc10", "ST1_SBc11", "ST1_SBc12", "ST1_SBc13", "ST1_SBc14", "ST1_Dummy37", "ST1_DASS1", "ST1_DASS2", "ST1_DASS3", "ST1_DASS4", "ST1_DASS5", "ST1_DASS6", "ST1_DASS7", "ST1_DASS8", "ST1_DASS9", "ST1_DASS10", "ST1_DASS11", "ST1_DASS12", "ST1_DASS13", "ST1_DASS14", "ST1_DASS15", "ST1_DASS16", "ST1_DASS17", "ST1_DASS18", "ST1_DASS19", "ST1_DASS20", "ST1_DASS21", "ST1_Dummy38", "ST1_TCF1", "ST1_TCF2", "ST1_TCF3", "ST1_TCF4", "ST1_TCF5", "ST1_TCF6", "ST1_TCF7", "ST1_TCF8"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns2",{{"ST1_SID SXXX", "ST1_SID"}}),
    #"FilteredRows" = Table.SelectRows(#"Renamed Columns", each [ST1_NO] <> "HKU_"),
    #"Sorted Rows" = Table.Sort(#"FilteredRows",{{"ST1_NO", Order.Ascending}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Sorted Rows",{{"Date modified", "ST1_Date_entry"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"ST1_Date_entry", type date}})
in
    #"Changed Type"